Repository alkcorp/GTplusplus, pull requests merged in 2018-04, with the labels that each got.

#242 Rewrite Exotic Seed Farmer as Exotic Seed Module
  src/Java/gtPlusPlus/xmod/sc2/HANDLER_SC2.java
  src/Java/gtPlusPlus/xmod/sc2/items/ItemCartModuleEx.java
  src/Java/gtPlusPlus/xmod/sc2/modules/IExoticCropModule.java
  src/Java/gtPlusPlus/xmod/sc2/modules/ModuleExoticSeeds.java
  src/Java/gtPlusPlus/xmod/sc2/modules/workers/tools/ModuleExoticFarmer.java
  src/Java/gtPlusPlus/xmod/sc2/modules/workers/tools/ModuleExoticFarmerUpgraded.java
  src/Java/gtPlusPlus/xmod/sc2/slots/SlotExoticSeed.java
  src/Java/vswe/stevescarts/ModuleData/GppModuleData.java
  src/Java/vswe/stevescarts/ModuleData/ModuleDataLoader.java
  src/resources/assets/stevescarts/textures/items/crop_exotic_seeds_icon.png
Labels: enhancement/suggestion/idea, major

#249 Fix alloy smelter recipes consuming molds
  src/Java/gtPlusPlus/xmod/gregtech/loaders/RecipeGen_AlloySmelter.java
Labels: Bug Fix, minor

#247 Frames by bartimaeusnek
  src/Java/gtPlusPlus/xmod/forestry/bees/items/FR_ItemRegistry.java
  src/Java/gtPlusPlus/xmod/forestry/bees/items/MB_FrameType.java
  src/Java/gtPlusPlus/xmod/forestry/bees/recipe/FR_Gregtech_Recipes.java
  src/resources/assets/miscutils/lang/de_DE.lang
  src/resources/assets/miscutils/lang/en_US.lang
  src/resources/assets/miscutils/textures/items/frameArborists.png
  src/resources/assets/miscutils/textures/items/frameDecaying.png
  src/resources/assets/miscutils/textures/items/frameSlowing.png
  src/resources/assets/miscutils/textures/items/frameStabilizing.png
  src/resources/assets/miscutils/textures/items/frameUseless.png
Labels: enhancement/suggestion/idea

#244 Rewrite Power Sub-Station machine structure
  src/Java/gtPlusPlus/xmod/gregtech/api/enums/GregtechItemList.java
  src/Java/gtPlusPlus/xmod/gregtech/common/blocks/GregtechMetaCasingBlocks2.java
  src/Java/gtPlusPlus/xmod/gregtech/common/blocks/GregtechMetaCasingBlocks3.java
  src/Java/gtPlusPlus/xmod/gregtech/common/blocks/textures/CasingTextureHandler2.java
  src/Java/gtPlusPlus/xmod/gregtech/common/blocks/textures/CasingTextureHandler3.java
  src/Java/gtPlusPlus/xmod/gregtech/common/blocks/textures/TexturesGtBlock.java
  src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/storage/GregtechMetaTileEntity_PowerSubStationController.java
  src/resources/assets/miscutils/lang/en_US.lang
  src/resources/assets/miscutils/textures/blocks/redox/redox1.png
  src/resources/assets/miscutils/textures/blocks/redox/redox2.png
  src/resources/assets/miscutils/textures/blocks/redox/redox3.png
  src/resources/assets/miscutils/textures/blocks/redox/redox4.png
  src/resources/assets/miscutils/textures/blocks/redox/redox5.png
  src/resources/assets/miscutils/textures/blocks/redox/redox6.png
Labels: Bug Fix, Work In Progress [W.I.P], enhancement/suggestion/idea, major

#258 Changed described size of Alloy Blast Smelter
  src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GregtechMetaTileEntity_AlloyBlastSmelter.java
Labels: Visual Error [Doesn't effect gameplay], enhancement/suggestion/idea, minor
