Repository alkcorp/GTplusplus, pull requests merged in 2018-05, with the labels that each got.

#264 Fix for Crash with latest GT and GT++.
  src/Java/gtPlusPlus/core/recipe/common/CI.java
  src/Java/gtPlusPlus/xmod/gregtech/HANDLER_GT.java
Labels: Bug Fix, major

#269 fix molten.sodium issue
  src/Java/gtPlusPlus/core/material/Material.java
  src/Java/gtPlusPlus/core/recipe/common/CI.java
  src/Java/gtPlusPlus/core/util/minecraft/MaterialUtils.java
Labels: Bug Fix, major

#270 DevCommandFix
  src/Java/gtPlusPlus/GTplusplus.java
  src/Java/gtPlusPlus/core/commands/CommandMath.java
Labels: Bug Fix, minor

#271 fix NEI crash on recipe search
  src/Java/gregtech/api/util/Recipe_GT.java
Labels: Bug Fix, major

#259 Files sent to me by Draknyte1 to create a pull request
  src/Java/gtPlusPlus/core/recipe/RECIPES_GREGTECH.java
  src/Java/gtPlusPlus/core/recipe/RECIPES_Machines.java
  src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/storage/GregtechMetaTileEntity_PowerSubStationController.java
Labels: Semi-Complete, Work In Progress [W.I.P], enhancement/suggestion/idea, major

#273 Codeenvy
  src/Java/gtPlusPlus/GTplusplus.java
  src/Java/gtPlusPlus/core/common/CommonProxy.java
  src/Java/gtPlusPlus/core/handler/BookHandler.java
  src/Java/gtPlusPlus/core/handler/COMPAT_HANDLER.java
  src/Java/gtPlusPlus/core/handler/OldCircuitHandler.java
  src/Java/gtPlusPlus/core/item/ModItems.java
  src/Java/gtPlusPlus/core/item/general/rfchargingpack/ChargingPackBase.java
  src/Java/gtPlusPlus/core/recipe/RECIPES_GREGTECH.java
  src/Java/gtPlusPlus/core/recipe/RECIPES_Machines.java
  src/Java/gtPlusPlus/core/recipe/RECIPES_Old_Circuits.java
  src/Java/gtPlusPlus/core/recipe/common/CI.java
  src/Java/gtPlusPlus/preloader/Preloader_GT_OreDict.java
  src/Java/gtPlusPlus/xmod/gregtech/common/blocks/GregtechMetaCasingBlocks3.java
  src/Java/gtPlusPlus/xmod/gregtech/common/blocks/textures/CasingTextureHandler3.java
  src/Java/gtPlusPlus/xmod/gregtech/common/blocks/textures/TexturesGtBlock.java
  src/Java/gtPlusPlus/xmod/gregtech/common/items/MetaGeneratedGregtechItems.java
  src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/generators/ULV/GT_MetaTileEntity_ULV_CombustionGenerator.java
  src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/generators/ULV/GT_MetaTileEntity_ULV_GasTurbine.java
  src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/generators/ULV/GT_MetaTileEntity_ULV_SteamTurbine.java
  src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_IndustrialMultiMachine.java
  src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_IndustrialVacuumFreezer.java
  src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/advanced/GregtechMetaTileEntity_Adv_EBF.java
  src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/advanced/GregtechMetaTileEntity_Adv_Implosion.java
  src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GT4Entity_AutoCrafter.java
  src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GregtechMetaTileEntityTreeFarm.java
  src/Java/gtPlusPlus/xmod/gregtech/registration/gregtech/Gregtech4Content.java
  src/Java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechAdvancedMixer.java
  src/resources/assets/gregtech/textures/blocks/iconsets/GAS_TURBINE_SIDE_ACTIVE.png
  src/resources/assets/gregtech/textures/blocks/iconsets/GAS_TURBINE_SIDE_ACTIVE.png.mcmeta
  src/resources/assets/gregtech/textures/blocks/iconsets/STEAM_TURBINE_SIDE_ACTIVE.png
  src/resources/assets/gregtech/textures/blocks/iconsets/STEAM_TURBINE_SIDE_ACTIVE.png.mcmeta
  src/resources/assets/gregtech/textures/gui/PowerSubStation.png
  src/resources/assets/miscutils/textures/blocks/TileEntities/MACHINE_CASING_ADVANCED_CRYOGENIC.png
  src/resources/assets/miscutils/textures/blocks/TileEntities/MACHINE_CASING_ADVANCED_VOLCANUS.png
  src/resources/assets/miscutils/textures/blocks/TileEntities/STEAM_TURBINE_SIDE_ACTIVE.png
  src/resources/assets/miscutils/textures/blocks/TileEntities/STEAM_TURBINE_SIDE_ACTIVE.png.mcmeta
Labels: Bug Fix, Semi-Complete, enhancement/suggestion/idea, major
